apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloappcentral2
  namespace: argocd
spec:
  source:
    path: application2
    repoURL: https://github.com/VillandryCalderon/Service.git
    targetRevision: HEAD
  destination:
    server: 'https://aks-antstesdos-dfce685b.hcp.centralus.azmk8s.io:443'
    namespace: kube-system
  project: default