apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloapp2
  namespace: argocd
spec:
  source:
    path: application2
    repoURL: https://github.com/VillandryCalderon/Service.git
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  project: default